### ISSUE TITLE
Uncaught Exception: TypeError when starting electron example

### ISSUE THREAD

**Issue by satlus** [Morgan-Stanley/desktopJS#65]
When starting the electron example from the ./web directory the app throws an error

Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from /Users/ripty/git/desktopJS/examples/electron\..\web\favicon.ico
    at ElectronContainer.addTrayIcon (../git/desktopJS/dist/desktop.js:775:20)
    at App.createWindow (../git/desktopJS/examples/electron/electron.js:12:15)
    at emitTwo (events.js:130:20)
    at App.emit (events.js:213:7)

Test Environment
OS: MacOS 10.13.1
Electron: 1.6.11, 1.8.1

This appears to be related to https://github.com/electron/electron/issues/7657, specifically an issue with conversion of a string to image.

**Comment by satlus** [comment]
The issue was not reproducible on windows 10, with electron v 1.7.1
